### ISSUE TITLE
Global audit: Fauxhai platform version

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-wrap#92]
In multiple cookbooks, fauxhai is being explicitly set to pretty old OS X versions. This is a global note to fix them.

**Comment by aramprice** [comment]
We might also want to audit `.travis.yml` to ensure that we are using the lates OSX version:

```yaml
---
language: objective-c # <= forces OS X
osx_image: xcode7.3 # <= forces version 10.11
# ...
```
